[[language]]
name = "rust"

[language-server.rust-analyzer.config]
check = { command = "clippy" } 
rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"] }
procMacro = { ignored = { "leptos_macro" = [ "server" ] }}

[language-server.omnisharp]
command = "dotnet"
args = [ "/opt/omnisharp/OmniSharp.dll", "--languageserver"]
